### ISSUE TITLE
Downloaded images getting deleted randomly after few days

### ISSUE THREAD

**Issue by ishdemon** [b-lam/Resplash#94] opened 2020-02-07 11:47 UTC
its happening on my oneplus 6T but doesn't happen in my other phone. I saw in code request.allowScanningByMediaScanner(); but somehow its still getting auto deleted by system

**Comment by Garis33** [comment] 2020-03-01 20:52
I believe the same the same is happening to me. I have noticed downloaded wallpapers being deleted after exactly one week. This wasn't happening on my Pixel XL but happening on Pixel 4 XL. Can't find anything in the settings for this.

**Comment by b-lam** [comment] 2020-06-22 18:52
This was caused due to a change in devices on Android Q+ where "allowScanningByMediaScanner" gets ignored causing the system to periodically remove files that it thinks have been forgotten. This should be fixed in v3.0.0

**Closed by b-lam** 2020-06-22 18:52 UTC

**Comment by ishdemon** [comment] 2020-06-22 18:59
Thanks. Would be happy to know how to fix it cause it happens in some of my
apps too.

**Comment by b-lam** [comment] 2020-06-22 19:34
@ishdemon The problem is described in this post (https://medium.com/@mkaflowski/disappearing-files-downloaded-by-downloadmanager-7c9ee5c6a66a). Unfortunately there isn't much you can do if you are using the system DownloadManager on Android Q+ other than saving to the Downloads directory. What I ended up doing was writing my own downloader that uses MediaStore.
